#  mkdocs serve -f mkdocs.yml --dev-addr=127.0.0.1:8000
site_name:  آزمایشگاه مهندسی نرم افزار هوشمند
site_url: https://m-zakeri.github.io/services/fa/
site_description: آزمایشگاه مهندسی نرم افزار هوشمند - دانشگاه صنعتی امیرکبیر (پلی تکنیک تهران)
site_author: مرتضی ذاکری
copyright: 2025 - 2024 &copy; 
  تمامی حقوق محفوظ است.   
  آزمایشگاه مهندسی نرم افزار هوشمند - دانشگاه صنعتی امیرکبیر (پلی تکنیک تهران)

docs_dir: docs/fa/

theme:
    name: material
    language: fa
    font:
        text: Vazirmatn
    logo: assets/ceaut.png
    #favicon: images/favicon.png
    features:
      - content.tooltips
      # Navigation features
      - navigation.indexes
      - navigation.instant
      - navigation.instant.progress
      - navigation.instant.preview
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.path
      - navigation.footer
      - toc.follow
      - toc.integrate
      # setup the search -----------------------------------------
      - search.suggest # search suggest completion
      - search.highlight # search highlight
      - search.share # deep linking

      # setup header ---------------------------------------------
      # - header.autohide # autohide header
      # - announce.dismiss
      - content.footnote.tooltips

  # Palette toggle for light mode
    palette:
      - scheme: default
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
   # Palette toggle for dark mode
      - scheme: slate
        toggle:
           icon: material/brightness-4
           name: Switch to light mode

    icon:
      annotation: material/arrow-right-circle


markdown_extensions:
  - abbr
  - admonition # support for admonitions ---> use this in markdown like this : !!! note "Note" or ??? warning "Warning"
  - pymdownx.details # support for admonitions with collapse
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #- pymdownx.blocks.caption
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower


nav:
    - خانه: index.md
    - خدمات: services.md
    - محصولات: products.md
    - افراد: people.md
    - بلاگ:
        - blog/index.md
    - گزارش خطا: 'https://github.com/m-zakeri/services/issues'



plugins:
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: true
      post_date_format: full
      pagination: true
      pagination_per_page: 10
  - search
  - social:
      enabled: !ENV [CI, false]

  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false


extra:
  alternate:
    - name: EN
      link: /en/
      lang: en
    - name: FA
      link: /fa/
      lang: fa
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mortazazakeri
    - icon: fontawesome/brands/telegram
      link: https://t.me/mztel
extra_css:
    - assets/styles.css

watch:
  - docs

